// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// G2G is the golang structure of table g2g for DAO operations like Where/Data.
type G2G struct {
	g.Meta `orm:"table:g2g, do:true"`
	Best   interface{} //
	Avg    interface{} //
	Ratio  interface{} //
	Count  interface{} //
	Ratio1 interface{} //
}
