// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Goldencham is the golang structure of table goldencham for DAO operations like Where/Data.
type Goldencham struct {
	g.Meta      `orm:"table:goldencham, do:true"`
	ToolChamber interface{} //
	MinDate     interface{} //
	MaxDate     interface{} //
	Recipe      interface{} //
}
