// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// GoldenchamData is the golang structure of table goldencham_data for DAO operations like Where/Data.
type GoldenchamData struct {
	g.Meta      `orm:"table:goldencham_data, do:true"`
	ToolChamber interface{} //
	Tool        interface{} //
	Cham        interface{} //
	MatchRatio  interface{} //
}
