// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Log is the golang structure of table log for DAO operations like Where/Data.
type Log struct {
	g.Meta     `orm:"table:log, do:true"`
	Id         interface{} // Log ID
	Passport   interface{} // Log Passport
	PassportId interface{} // Log Passport ID
	Time       *gtime.Time // Log Time
}
