// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Oer is the golang structure of table oer for DAO operations like Where/Data.
type Oer struct {
	g.Meta          `orm:"table:oer, do:true"`
	ToolChamberDate interface{} //
	StableSlot      interface{} //
	StableWafer     interface{} //
	Count           interface{} //
}
