// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Ooc is the golang structure of table ooc for DAO operations like Where/Data.
type Ooc struct {
	g.Meta      `orm:"table:ooc, do:true"`
	ToolChamber interface{} //
	LastDate    interface{} //
	OOC         interface{} //
}
