// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Pm is the golang structure of table pm for DAO operations like Where/Data.
type Pm struct {
	g.Meta       `orm:"table:pm, do:true"`
	ToolChamber  interface{} //
	RFTime       interface{} //
	Level        interface{} //
	Message      interface{} //
	AlarmChamber interface{} //
}
