// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Seasoning is the golang structure of table seasoning for DAO operations like Where/Data.
type Seasoning struct {
	g.Meta          `orm:"table:seasoning, do:true"`
	ToolChamberDate interface{} //
	StableSlot      interface{} //
	StableWafer     interface{} //
	Count           interface{} //
	One             interface{} //
}
