// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// G2GDao is the data access object for table g2g.
type G2GDao struct {
	table   string     // table is the underlying table name of the DAO.
	group   string     // group is the database configuration group name of current DAO.
	columns G2GColumns // columns contains all the column names of Table for convenient usage.
}

// G2GColumns defines and stores column names for table g2g.
type G2GColumns struct {
	Best   string //
	Avg    string //
	Ratio  string //
	Count  string //
	Ratio1 string //
}

// g2GColumns holds the columns for table g2g.
var g2GColumns = G2GColumns{
	Best:   "best",
	Avg:    "avg",
	Ratio:  "ratio",
	Count:  "count",
	Ratio1: "ratio1",
}

// NewG2GDao creates and returns a new DAO object for table data access.
func NewG2GDao() *G2GDao {
	return &G2GDao{
		group:   "default",
		table:   "g2g",
		columns: g2GColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *G2GDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *G2GDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *G2GDao) Columns() G2GColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *G2GDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *G2GDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *G2GDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
