// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"web_backend/internal/dao/internal"
)

// internalG2GDao is internal type for wrapping internal DAO implements.
type internalG2GDao = *internal.G2GDao

// g2GDao is the data access object for table g2g.
// You can define custom methods on it to extend its functionality as you wish.
type g2GDao struct {
	internalG2GDao
}

var (
	// G2G is globally public accessible object for table g2g operations.
	G2G = g2GDao{
		internal.NewG2GDao(),
	}
)

// Fill with you ideas below.
