// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"web_backend/internal/dao/internal"
)

// internalGoldenchamDao is internal type for wrapping internal DAO implements.
type internalGoldenchamDao = *internal.GoldenchamDao

// goldenchamDao is the data access object for table goldencham.
// You can define custom methods on it to extend its functionality as you wish.
type goldenchamDao struct {
	internalGoldenchamDao
}

var (
	// Goldencham is globally public accessible object for table goldencham operations.
	Goldencham = goldenchamDao{
		internal.NewGoldenchamDao(),
	}
)

// Fill with you ideas below.
