// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"web_backend/internal/dao/internal"
)

// internalGoldenchamDataDao is internal type for wrapping internal DAO implements.
type internalGoldenchamDataDao = *internal.GoldenchamDataDao

// goldenchamDataDao is the data access object for table goldencham_data.
// You can define custom methods on it to extend its functionality as you wish.
type goldenchamDataDao struct {
	internalGoldenchamDataDao
}

var (
	// GoldenchamData is globally public accessible object for table goldencham_data operations.
	GoldenchamData = goldenchamDataDao{
		internal.NewGoldenchamDataDao(),
	}
)

// Fill with you ideas below.
