// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"web_backend/internal/dao/internal"
)

// internalOerDao is internal type for wrapping internal DAO implements.
type internalOerDao = *internal.OerDao

// oerDao is the data access object for table oer.
// You can define custom methods on it to extend its functionality as you wish.
type oerDao struct {
	internalOerDao
}

var (
	// Oer is globally public accessible object for table oer operations.
	Oer = oerDao{
		internal.NewOerDao(),
	}
)

// Fill with you ideas below.
