// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"web_backend/internal/dao/internal"
)

// internalOocDao is internal type for wrapping internal DAO implements.
type internalOocDao = *internal.OocDao

// oocDao is the data access object for table ooc.
// You can define custom methods on it to extend its functionality as you wish.
type oocDao struct {
	internalOocDao
}

var (
	// Ooc is globally public accessible object for table ooc operations.
	Ooc = oocDao{
		internal.NewOocDao(),
	}
)

// Fill with you ideas below.
