// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"web_backend/internal/dao/internal"
)

// internalPmDao is internal type for wrapping internal DAO implements.
type internalPmDao = *internal.PmDao

// pmDao is the data access object for table pm.
// You can define custom methods on it to extend its functionality as you wish.
type pmDao struct {
	internalPmDao
}

var (
	// Pm is globally public accessible object for table pm operations.
	Pm = pmDao{
		internal.NewPmDao(),
	}
)

// Fill with you ideas below.
