// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"web_backend/internal/dao/internal"
)

// internalSeasoningDao is internal type for wrapping internal DAO implements.
type internalSeasoningDao = *internal.SeasoningDao

// seasoningDao is the data access object for table seasoning.
// You can define custom methods on it to extend its functionality as you wish.
type seasoningDao struct {
	internalSeasoningDao
}

var (
	// Seasoning is globally public accessible object for table seasoning operations.
	Seasoning = seasoningDao{
		internal.NewSeasoningDao(),
	}
)

// Fill with you ideas below.
