// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// G2G is the golang structure for table g2g.
type G2G struct {
	Best   string  `json:"best"   description:""`
	Avg    string  `json:"avg"    description:""`
	Ratio  float64 `json:"ratio"  description:""`
	Count  string  `json:"count"  description:""`
	Ratio1 float64 `json:"ratio1" description:""`
}
