// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// GoldenchamData is the golang structure for table goldencham_data.
type GoldenchamData struct {
	ToolChamber string `json:"toolChamber" description:""`
	Tool        string `json:"tool"        description:""`
	Cham        string `json:"cham"        description:""`
	MatchRatio  string `json:"matchRatio"  description:""`
}
