// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Goldencham is the golang structure for table goldencham.
type Goldencham struct {
	ToolChamber string `json:"toolChamber" description:""`
	MinDate     string `json:"minDate"     description:""`
	MaxDate     string `json:"maxDate"     description:""`
	Recipe      string `json:"recipe"      description:""`
}
