// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Oer is the golang structure for table oer.
type Oer struct {
	ToolChamberDate string `json:"toolChamberDate" description:""`
	StableSlot      int    `json:"stableSlot"      description:""`
	StableWafer     int    `json:"stableWafer"     description:""`
	Count           int    `json:"count"           description:""`
}
