// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Ooc is the golang structure for table ooc.
type Ooc struct {
	ToolChamber string `json:"toolChamber" description:""`
	LastDate    string `json:"lastDate"    description:""`
	OOC         string `json:"oOC"         description:""`
}
