// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Pm is the golang structure for table pm.
type Pm struct {
	ToolChamber  string  `json:"toolChamber"  description:""`
	RFTime       float64 `json:"rFTime"       description:""`
	Level        int     `json:"level"        description:""`
	Message      string  `json:"message"      description:""`
	AlarmChamber int     `json:"alarmChamber" description:""`
}
