// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Seasoning is the golang structure for table seasoning.
type Seasoning struct {
	ToolChamberDate string `json:"toolChamberDate" description:""`
	StableSlot      int    `json:"stableSlot"      description:""`
	StableWafer     int    `json:"stableWafer"     description:""`
	Count           int    `json:"count"           description:""`
	One             int    `json:"one"             description:""`
}
